### ISSUE TITLE
minor suggestions & update request to rust-microservice

### ISSUE THREAD

**Issue by zertyz** [diegopacheco/rust-playground#3]
Thanks for sharing your playground.

I just clicked "watch" to follow the progress.

It would be nice to add some reactive & event driven examples.

Also, the rust-microservice spikes seems to require a little update or doc revisitation. It is not running on my machine:

On terminal 1, ran:
```
[luiz@PLap rust-microservice]$ ./run-docker-postgress.sh & RUST_LOG=info RUST_BACKTRACE=1 cargo run --bin news-service
[1] 46166
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/news-service`
[2021-02-21T22:29:14Z INFO  actix_server::builder] Starting 8 workers
[2021-02-21T22:29:14Z INFO  actix_server::builder] Starting "actix-web-service-127.0.0.1:8080" service on 127.0.0.1:8080

PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-02-21 22:29:14.982 UTC [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-02-21 22:29:14.982 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-02-21 22:29:14.982 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2021-02-21 22:29:14.986 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-02-21 22:29:14.987 UTC [26] LOG:  database system was shut down at 2021-02-21 22:29:00 UTC
2021-02-21 22:29:14.991 UTC [1] LOG:  database system is ready to accept connections
```

On terminal 2:
```
[luiz@PLap ~]$ curl http://localhost:8080/news
curl: (52) Empty reply from server

```
Back to terminal 1:
```
2021-02-21 22:30:22.547 UTC [34] ERROR:  relation "news" does not exist at character 33
2021-02-21 22:30:22.547 UTC [34] STATEMENT:  SELECT id::text,url,'desc' FROM news
thread 'actix-rt:worker:0' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P01"), message: "relation \"news\" does not exist", detail: None, hint: None, position: Some(Original(33)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("parse_relation.c"), line: Some(1376), routine: Some("parserOpenTable") }) }', /home/luiz/CLionProjects/rust/git/rust-playground/rust-microservice/news-dao/src/lib.rs:53:79
stack backtrace:
   0: rust_begin_unwind
             at /build/rust/src/rustc-1.50.0-src/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /build/rust/src/rustc-1.50.0-src/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /build/rust/src/rustc-1.50.0-src/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /build/rust/src/rustc-1.50.0-src/library/core/src/result.rs:973:23
   4: news_dao::list_news::{{closure}}
             at ./news-dao/src/lib.rs:53:15
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rust/src/rustc-1.50.0-src/library/core/src/future/mod.rs:80:19
   6: news_service::endpoints::service::list_news::{{closure}}
             at ./news-service/src/service.rs:21:10
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rust/src/rustc-1.50.0-src/library/core/src/future/mod.rs:80:19
   8: <news_service::endpoints::list_news as actix_web::service::HttpServiceFactory>::register::list_news::{{closure}}
             at ./news-service/src/endpoints.rs:11:16
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rust/src/rustc-1.50.0-src/library/core/src/future/mod.rs:80:19
  10: <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/handler.rs:138:15
  11: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/handler.rs:247:20
  12: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/future/map.rs:55:37
  13: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/lib.rs:102:13
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /build/rust/src/rustc-1.50.0-src/library/core/src/future/future.rs:119:9
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /build/rust/src/rustc-1.50.0-src/library/core/src/future/future.rs:119:9
  16: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.12/src/future/either.rs:73:33
  17: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /build/rust/src/rustc-1.50.0-src/library/core/src/future/future.rs:119:9
  18: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/h1/dispatcher.rs:390:27
  19: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/h1/dispatcher.rs:758:38
  20: actix_http::service::State<T,S,B,X,U>::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/service.rs:660:32
  21: <actix_http::service::HttpServiceHandlerResponse<T,S,B,X,U> as core::future::future::Future>::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/service.rs:637:9
  22: <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-1.0.6/src/and_then.rs:101:34
  23: <actix_server::service::StreamService<T> as actix_service::Service>::call::{{closure}}
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.4/src/service.rs:85:33
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rust/src/rustc-1.50.0-src/library/core/src/future/mod.rs:80:19
  25: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:173:17
  26: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:14:9
  27: tokio::runtime::task::core::Core<T,S>::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/core.rs:158:13
  28: tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:107:27
  29: core::ops::function::FnOnce::call_once
             at /build/rust/src/rustc-1.50.0-src/library/core/src/ops/function.rs:227:5
  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /build/rust/src/rustc-1.50.0-src/library/std/src/panic.rs:322:9
  31: std::panicking::try::do_call
             at /build/rust/src/rustc-1.50.0-src/library/std/src/panicking.rs:379:40
  32: __rust_try
  33: std::panicking::try
             at /build/rust/src/rustc-1.50.0-src/library/std/src/panicking.rs:343:19
  34: std::panic::catch_unwind
             at /build/rust/src/rustc-1.50.0-src/library/std/src/panic.rs:396:14
  35: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/harness.rs:89:19
  36: tokio::runtime::task::raw::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:104:5
  37: tokio::runtime::task::raw::RawTask::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/raw.rs:66:18
  38: tokio::runtime::task::Notified<S>::run
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/task/mod.rs:169:9
  39: tokio::task::local::LocalSet::tick::{{closure}}
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:408:54
  40: tokio::coop::with_budget::{{closure}}
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:127:9
  41: std::thread::local::LocalKey<T>::try_with
             at /build/rust/src/rustc-1.50.0-src/library/std/src/thread/local.rs:272:16
  42: std::thread::local::LocalKey<T>::with
             at /build/rust/src/rustc-1.50.0-src/library/std/src/thread/local.rs:248:9
  43: tokio::coop::with_budget
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:120:5
  44: tokio::coop::budget
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:96:5
  45: tokio::task::local::LocalSet::tick
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:408:31
  46: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:532:16
  47: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
  48: tokio::task::local::LocalSet::with
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:442:9
  49: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:518:9
  50: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:392:9
  51: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rust/src/rustc-1.50.0-src/library/core/src/future/mod.rs:80:19
  52: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:131:58
  53: tokio::coop::with_budget::{{closure}}
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:127:9
  54: std::thread::local::LocalKey<T>::try_with
             at /build/rust/src/rustc-1.50.0-src/library/std/src/thread/local.rs:272:16
  55: std::thread::local::LocalKey<T>::with
             at /build/rust/src/rustc-1.50.0-src/library/std/src/thread/local.rs:248:9
  56: tokio::coop::with_budget
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:120:5
  57: tokio::coop::budget
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/coop.rs:96:5
  58: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:131:35
  59: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:213:29
  60: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/macros/scoped_tls.rs:63:9
  61: tokio::runtime::basic_scheduler::enter
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:213:5
  62: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/basic_scheduler.rs:123:9
  63: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/mod.rs:444:34
  64: tokio::runtime::context::enter
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/context.rs:72:5
  65: tokio::runtime::handle::Handle::enter
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:76:9
  66: tokio::runtime::Runtime::block_on
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/mod.rs:441:9
  67: tokio::task::local::LocalSet::block_on
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/task/local.rs:353:9
  68: actix_rt::runtime::Runtime::block_on
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/runtime.rs:89:9
  69: actix_rt::arbiter::Arbiter::new::{{closure}}
             at /home/luiz/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/arbiter.rs:137:31
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by diegopacheco** [comment]
You need to run the migrations:
https://github.com/diegopacheco/rust-playground/tree/master/rust-microservice/news-migrations
