### ISSUE TITLE
jni-fun Creates a java exception after cloning and running via ./run.sh

### ISSUE THREAD

**Issue by EstiaanJ** [diegopacheco/rust-playground#4]
### Error Message
`LD_LIBRARY_PATH=/home/<username>/Documents/GitHub/jni-fun/target/debug/
Exception in thread "main" java.lang.UnsatisfiedLinkError: no main in java.library.path: [/home/<username>/Documents/GitHub/jni-fun/target/debug/, /usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2673)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at HelloWorld.<clinit>(HelloWorld.java:5)`

### System Details
Linux Kernel: 5.10.0-20-amd64
Debian: 11
Java: 11.0.16
Rust: 1.66.1

**Comment by EstiaanJ** [comment]
Oh you have to build the rust first, got it
